services:
  jupyterlab: 
    image: jkropko/contrans2023
    env_file: 
      - .env
    ports:
      - "8890:8888"
      - "8050:8050"
    volumes:
      - ./:/contrans2023
      - ./settings.txt:/root/.jupyter/lab/user-settings/@jupyterlab/notebook-extension/tracker.jupyterlab-settings
    networks:
      - dbnetwork

  postgres:
    image: postgres:latest
    env_file: 
      - .env
    ports: 
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - dbnetwork
  
  
  mongo:
    image: mongo:latest
    env_file:
      - .env
    volumes: 
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - dbnetwork
volumes:
  postgresdata:
  mongodata:

networks:
  dbnetwork: