services:
  jupyterlab: 
    image: jkropko/tiktok
    env_file: 
      - .env
    ports:
      - "8888:8888"
      - "8050:8050"
    volumes:
      - ./:/tiktok
      - ./settings.txt:/root/.jupyter/lab/user-settings/@jupyterlab/notebook-extension/tracker.jupyterlab-settings
    networks:
      - dbnetwork

  postgres:
    image: postgres:latest
    env_file: 
      - .env
    ports: 
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - dbnetwork
  
volumes:
  postgresdata:

networks:
  dbnetwork: